plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-coffeescript
  
# SEO Stuff
author: Simon LANDAIS
description: Site Internet personnel sur l'usage raisonné du numérique, le numérique responsable
lang: fr
locale: fr_FR
url: "https://www.numerique-raisonne.fr"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20

sass:
    style: compressed

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
