name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: HTML/CSS/JS Minifier
      uses: devatherock/minify-js@v1.0.2
      with:
        directory: 'assets/css'      # Optional
        output: 'assets/css'  # Optional
        add_suffix: false     # Optional
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: HTML/CSS/JS Minifier
      uses: devatherock/minify-js@v1.0.2
      with:
        directory: 'assets/css'      # Optional
        output: 'assets/css'  # Optional
        add_suffix: false     # Optional
